<div id="content_wrapper">
	<div class="constrain">
		<div class="thumb_container">
			<h2>Portland Bridges <span>{iPhone Wallpapers}</span></h2>
			<span class="setMeta">
				<p>We love PDX bridges and iPhones (not to mention iPod Touch&rsquo;s, too). Why not have both in the palm of your hand? We made a set of 6 iPhone Wallpapers of our favorite Portland Bridges just for you to switch up on a nice rainy day. Hope you enjoy them!</p>
				<p>To read more about Portland's unique bridgework and see some amazing photos, check out <a class="external" href="http://www.portlandbridges.com/">PortlandBridges.com</a> and <a class="external" href="http://www.travelportland.com/media/genmedkit/gm_bridges_fountains.html">TravelPotland.com</a>.</p>
			</span>
			<img id="big_thumb" src="images/burnside.jpg" alt="default" />
			<div class="thumb active">
				<img src="images/burnside.jpg" alt="Burnside Bridge" />
				<p>Burnside Bridge</p>
				<a class="wiki external" href="http://en.wikipedia.org/wiki/Burnside_Bridge" title="Burnside Bridge Wikipedia Article"><img src="images/Wikipedia.png" alt="Wikipedia This!" /></a>
			</div>
			<div class="thumb">
				<img src="images/fremont.jpg" alt="Fremont Bridge" />
				<p>Fremont Bridge</p>
				<a class="wiki external" href="http://en.wikipedia.org/wiki/Fremont_Bridge_(Portland)" title="Fremont Bridge Wikipedia Article"><img src="images/Wikipedia.png" alt="Wikipedia This!" /></a>
			</div>
			<div class="thumb">
				<img src="images/hawthorne.jpg" alt="Hawthorne Bridge" />
				<p>Hawthorne Bridge</p>
				<a class="wiki external" href="http://en.wikipedia.org/wiki/Hawthorne_Bridge" title="Hawthorne Bridge Wikipedia Article"><img src="images/Wikipedia.png" alt="Wikipedia This!" /></a>
			</div>
			<div class="thumb">
				<img src="images/marquam.jpg" alt="Marquam Bridge" />
				<p>Marquam Bridge</p>
				<a class="wiki external" href="http://en.wikipedia.org/wiki/Marquam_Bridge" title="Marquam Bridge Wikipedia Article"><img src="images/Wikipedia.png" alt="Wikipedia This!" /></a>
			</div>
			<div class="thumb">
				<img src="images/stJohns.jpg" alt="St. Johns Bridge" />
				<p>St. Johns Bridge</p>
				<a class="wiki external" href="http://en.wikipedia.org/wiki/St._Johns_Bridge" title="St. Johns Bridge Wikipedia Article"><img src="images/Wikipedia.png" alt="Wikipedia This!" /></a>
			</div>
			<div class="thumb">
				<img src="images/steel.jpg" alt="Steel Bridge" />
				<p>Steel <br/>Bridge</p>
				<a class="wiki external" href="http://en.wikipedia.org/wiki/Steel_Bridge" title="Steel Bridge Wikipedia Article"><img src="images/Wikipedia.png" alt="Wikipedia This!" /></a>
			</div>
			<a href="#" class="button donate"><span>I Want This Set!</span>GET IT</a>
			<div class="clear"><!-- --></div>
		</div>
		<div class="adsense">
			<h3><span>Check Out</span>Some Related Links</h3>
			<img width="225" src="images/adsense.png" alt="adsense" />
		</div>
	</div>
</div>
