<div id="header_wrapper">
	<div class="constrain">
		<h1>Logo</h1>
		<ul class="nav social">
			<li><a href="#">Twitter</a></li>
			<li><a href="#">Facebook</a></li>
			<li><a href="#">Behance</a></li>
			<li><a href="#">Virb</a></li>
			<li><a href="#">RSS</a></li>
		</ul>
		<div class="clear"><!-- --></div>
		<ul class="nav main">
			<li><a href="#">FAQ</a></li>
			<li><a class="external" href="https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=7432278">Donate</a></li>
		</ul>
		<div class="clear"><!-- --></div>
	</div>
</div>
<div id="content_wrapper">
	<div class="constrain">
		<div class="thumb_container">
			<h2>Bridges</h2>
			<img id="big_thumb" src="images/image01.jpg" alt="defalut" />
			<div class="thumb active">
				<img src="images/image01.jpg" alt="defalut" />
				<p>Title</p>
			</div>
			<div class="thumb">
				<img src="images/image02.jpg" alt="defalut" />
				<p>Title</p>
			</div>
			<div class="thumb">
				<img src="images/image03.jpg" alt="defalut" />
				<p>Title</p>
			</div>
			<div class="thumb">
				<img src="images/image04.jpg" alt="defalut" />
				<p>Title</p>
			</div>
			<div class="thumb">
				<img src="images/image05.jpg" alt="defalut" />
				<p>Title</p>
			</div>
			<div class="thumb">
				<img src="images/image06.jpg" alt="defalut" />
				<p>Title</p>
			</div>
			<div class="clear"><!-- --></div>
		</div>
		<div class="adsense">
			<img width="225" src="images/adsense.png" alt="adsense" />
		</div>
		<a href="#" class="button donate">Donate To Set</a>
	</div>
</div>
<div id="footer_wrapper">
	<div class="constrain">
		<ul class="featured">
			<li>
				<img src="images/defalut.gif" alt="defalut" />
				<p>Name</p>
				<em>Title</em>
				<div class="clear"><!-- --></div>
			</li>
			<li>
				<img src="images/defalut.gif" alt="defalut" />
				<p>Name</p>
				<em>Title</em>
				<div class="clear"><!-- --></div>
			</li>
			<li>
				<img src="images/defalut.gif" alt="defalut" />
				<p>Name</p>
				<em>Title</em>
				<div class="clear"><!-- --></div>
			</li>
		</ul>
		<div class="adsense">
			<img width="175" src="images/adsense.png" alt="adsense" />
		</div>
		<form id="contact" action="#">
			<fieldset>
				<legend>Contact Us</legend>
				<label for="first_name">First</label>
				<input type="text" id="first_name" name="first_name" />
				<label for="last_name">First</label>
				<input type="text" id="last_name" name="last_name" />
				<label for="message">Message</label>
				<textarea id="message" name="message"></textarea>
			</fieldset>
		</form>
		<div class="clear"><!-- --></div>
		<ul class="nav foot">
			<li><a href="#">Link</a></li>
			<li><a href="#">Link</a></li>
			<li><a href="#">Link</a></li>
			<li><a href="#">Link</a></li>
		</ul>
		<div class="clear"><!-- --></div>
		<p class="copyright">copyright</p>
	</div>
	<div class="hidden">
 		<div id="donate">
 			<p>Please Donate:</p>
 			<a class="button external" href="https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=7435401">Donate</a>
 			<p>Download Set:</p>
 			<a class="button" href="#">Download</a>
 		</div>
 	</div>
</div>
