<!-- Footer -->
<div id="footer_wrapper">
	<div class="constrain">
		<ul class="featured">
			<h3><span>Meet Our Creative Friends</span>The Local Talent</h3>
			<li>
				 <a class="external" href="http://www.johnnylefilms.com/"><img src="/images/JLF_BEHANCE_GREY_bigger.jpg" alt="Johnny Le Films" /></a>
		         <p><a class="external" href="http://www.johnnylefilms.com/">Johnny Le</a></p>
		         <em>NW Filmmaker, Producer & Director who wrote & directed &ldquo;Lick The Short&rdquo;.</em>
				<div class="clear"><!-- --></div>
			</li>
			<li>
				<a class="external" href="http://www.nuevaforma.com/"><img src="/images/nfavatar_bigger.png" alt="Nueva Forma" /></a>
				<p><a class="external" href="http://www.nuevaforma.com/">Nueva Forma</a></p>
		      	<em>NW Eclectic Music Label that offers a variety of acousmatic pop, IDM, dub, click house, ambient, and hiphop music.</em>
				<div class="clear"><!-- --></div>
			</li>
			<li>
				<a class="external" href="http://www.findsubstance.com/"><img src="/images/tree_1c_cream_bg_bigger.png" alt="Substance, Inc." /></a>
				<p><a class="external" href="http://www.findsubstance.com/">Substance, Inc.</a></p>
				<em>SE Interactive Brand Strategy Company. The passionate voice of interactive brand experiences.</em>
				<div class="clear"><!-- --></div>
			</li>
		</ul>
		<div class="adsense">
			<h3>Looking For Something?</h3>
			<script type="text/javascript"><!--
			google_ad_client = "pub-6171381847099711";
			/* 160x90, created 8/13/09 */
			google_ad_slot = "8056953403";
			google_ad_width = 160;
			google_ad_height = 90;
			//-->
			</script>
			<script type="text/javascript"
			src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
			</script>
		</div>
		<form id="contact" action="/contact/mail" method="post">
			<fieldset>
				<legend><span>Be Our Friends</span>Get In Touch With Us</legend>
				<label for="first_name">First</label>
				<input type="text" id="first_name" name="first_name" />
				<label for="last_name">Last</label>
				<input type="text" id="last_name" name="last_name" />
				<label for="last_name">Email</label>
				<input type="text" id="email" name="email" />
				<label for="message">Message</label>
				<textarea id="message" name="message"></textarea>
				<input type="submit" id="submit" name="submit" value="Send" class="button"/>
			</fieldset>
		</form>
		<div class="clear"><!-- --></div>
		<ul class="nav foot">
			<li><a href="/">Home</a></li>
			|
			<li><a href="/faq/">FAQ</a></li>
			|
			<li><a class="external" href="https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=7432278">Donate</a></li>
		</ul>
		<ul class="social">
			<li><a href="http://www.twitter.com/illustratedPDX"><img src="/images/social24/twitter.png" /></a></li>
			<li><a href="http://www.facebook.com/illustratedpdx"><img src="/images/social24/facebook.png" /></a></li>
			<li><a href="http://www.youtube.com/illustratedportland"><img src="/images/social24/youtube.png" /></a></li>
			<li><a href="http://www.vimeo.com/illustratedpdx"><img src="/images/social24/vimeo.png" /></a></li>
			<li><a href="/blog/rss"><img src="/images/social24/feed.png" /></a></li>
		</ul>
		<p class="copyright">&copy;2009, Kellan Craddock, Jerylyn Brei, & Jessica Tsuji. ALL RIGHTS RESERVED.</p>
		<div class="clear"><!-- --></div>
	</div>
	<!--Overlay-->
	<div class="hidden">
 		<div id="donate">
			<h3>Wanna Help Us?</h3>
			<p>This set is <strong>free</strong> but if you&rsquo;re in the generous mood, we&rsquo;d <em>greatly</em> appreciate it.</p>
 			<a class="button donate external" href="https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=7435401">Donate</a>
			<h3>Get The Set</h3>
			<p>Portland Bridges iPhone Wallpapers</p>
 			<a class="button download" href="/sets/download">Download</a>
 			<span id="creativeCommons">
 				<a class="ccImg" rel="license" href="http://creativecommons.org/licenses/by-nc-nd/3.0/us/"><img alt="Creative Commons License" style="border-width:0" src="http://creativecommons.org/images/public/somerights20.png" /></a>
	 			<span class="ccMeta" xmlns:dc="http://purl.org/dc/elements/1.1/" property="dc:title">Illustrated Portland Bridge iPhone Wallpaper Set</span> by <a xmlns:cc="http://creativecommons.org/ns#" href="http://www.illustratedportland.com" property="cc:attributionName" rel="cc:attributionURL">Jessica Tsuji, Kellan Craddock, &amp; Jerylyn Brei</a> is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by-nc-nd/3.0/us/">Creative Commons Attribution-Noncommercial-No Derivative Works 3.0 United States License</a>
	 		</span>
 		</div>
 	</div>
</div>