<div id="content_wrapper">
	<div class="constrain">
		<div class="faq_container">
			<h2>Frequently Asked Questions</h2>
			<ul>
				<li>
					<strong>How do you install an iPhone Wallpaper?</strong>
					<p>First, download the wallpaper set of your choice which is in a .zip file format.  Use StuffitExpander or other Unzipping software to expand the files. Select the wallpaper you would like to use. Open iPhoto and drag the wallpaper file you would like to use into iPhoto. Plug in your iPhone or iPod touch, open iTunes and sync your iPhoto photos.</p>
				</li>
				<li>
					<strong>How do you install an iPhone Wallpaper?</strong>
					<p>First, download the wallpaper set of your choice which is in a .zip file format.  Use StuffitExpander or other Unzipping software to expand the files. Select the wallpaper you would like to use. Open iPhoto and drag the wallpaper file you would like to use into iPhoto. Plug in your iPhone or iPod touch, open iTunes and sync your iPhoto photos.</p>
				</li>
				<li>
					<strong>How do you install an iPhone Wallpaper?</strong>
					<p>First, download the wallpaper set of your choice which is in a .zip file format.  Use StuffitExpander or other Unzipping software to expand the files. Select the wallpaper you would like to use. Open iPhoto and drag the wallpaper file you would like to use into iPhoto. Plug in your iPhone or iPod touch, open iTunes and sync your iPhoto photos.</p>
				</li>
				<li>
					<strong>How do you install an iPhone Wallpaper?</strong>
					<p>First, download the wallpaper set of your choice which is in a .zip file format.  Use StuffitExpander or other Unzipping software to expand the files. Select the wallpaper you would like to use. Open iPhoto and drag the wallpaper file you would like to use into iPhoto. Plug in your iPhone or iPod touch, open iTunes and sync your iPhoto photos.</p>
				</li>
			</ul>
		</div>
		<div class="adsense">
			<h3><span>Check Out</span>Some Related Links</h3>
			<img width="225" src="images/adsense.png" alt="adsense" />
		</div>
	</div>
</div>
