<div id="content_wrapper">
	<div class="constrain">
		<div class="faq_container">
			<h2>Frequently Asked Questions</h2>
			<ul>
				<li>
					<strong>How do you install an iPhone Wallpaper?</strong>
					<p>First, download the wallpaper set of your choice which is in a .zip file format.  Use StuffitExpander or other Unzipping software to expand the files. Select the wallpaper you would like to use. Open iPhoto and drag the wallpaper file you would like to use into iPhoto. Plug in your iPhone or iPod touch, open iTunes and sync your iPhoto photos.</p>
				</li>
				<li>
					<strong>How do I become a Creative Friend?</strong>
					<p>Fill out our form at the bottom of this page and get in touch with us.</p>
				</li>
				<li>
					<strong>Where can I find good Doughnuts in Portland?</strong>
					<p>VooDoo Doughnuts.</p>
				</li>
				<li>
					<strong>Where is the sun in Portland?</strong>
					<p>Relax, he&rsquo;s here. He&rsquo;s just taking a break.</p>
				</li>
			</ul>
		</div>
		<div class="adsense">
			<h3><span>Check Out</span>Some Related Links</h3>
			<!--AdSense-->
			<script type="text/javascript"><!--
				google_ad_client = "pub-6171381847099711";
				/* 160x600, created 8/13/09 */
				google_ad_slot = "5781379349";
				google_ad_width = 160;
				google_ad_height = 600;
				//-->
			</script>
			<script type="text/javascript" src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
			</script>
			<!--AdSense-->
		</div>
	</div>
</div>
