<div id="content_wrapper">
	<!--Alerts-->
	<?php if ($this->alert) { ?>
	<div id="alertMessage" class="constrain alert">
		<h2><?= $this->alert ?></h2>
	</div>
	<?php } ?>
	<div class="download_container constrain">
		<h2>Download:</h2>
		<a href="/download/iphone_bridges.zip" class="button">Zip Files</a>
		<a href="/" class="button">Go Home</a>
		<span id="creativeCommons">
			<a class="ccImg" rel="license" href="http://creativecommons.org/licenses/by-nc-nd/3.0/us/"><img alt="Creative Commons License" style="border-width:0" src="http://creativecommons.org/images/public/somerights20.png" /></a>
			<span class="ccMeta" xmlns:dc="http://purl.org/dc/elements/1.1/" property="dc:title">Illustrated Portland Bridge iPhone Wallpaper Set</span> by <a xmlns:cc="http://creativecommons.org/ns#" href="http://www.illustratedportland.com" property="cc:attributionName" rel="cc:attributionURL">Jessica Tsuji, Kellan Craddock, &amp; Jerylyn Brei</a> is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by-nc-nd/3.0/us/">Creative Commons Attribution-Noncommercial-No Derivative Works 3.0 United States License</a>
		</span>
	</div>
</div>