		<?= $this->render('header.phtml') ?>
		<!-- Content -->
		<?= $this->layout()->content ?>
		<?= $this->render('footer.phtml') ?>
	</div>
	<!--Analytics -->
	<script type="text/javascript">
var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));
</script>
<script type="text/javascript">
try {
var pageTracker = _gat._getTracker("UA-1915473-7");
pageTracker._trackPageview();
} catch(err) {}</script>
</body>
</html>